Repository SJJC-Team/whooshing.system-manager, pull requests merged in 2025-01, with the labels that each got.

#8 0.1.3 developer james diagram update
  diagrams/1.模块间通信加密机制批注.png
  raw/diagrams/系统加密.graffle
Labels: enhancement

#10 V0.1.3.3 添加1.1编号以区分批注图片
  diagrams/1.0模块间通信加密机制.png
  diagrams/1.1模块间通信加密机制批注.png
  raw/diagrams/系统加密.graffle
Labels: enhancement

#11 0.1.4 更新通讯机制设计图
  README.md
  diagrams/1.0.模块间通信加密机制.png
  diagrams/1.0模块间通信加密机制.png
  diagrams/1.1.模块通信加密机制批注.png
  diagrams/1.1模块间通信加密机制批注.png
  diagrams/2.从属服务器.png
  diagrams/3.用户数据加密机制.png
  diagrams/4.模块间通信加密时序.png
  raw/diagrams/加密机制.graffle
  raw/diagrams/系统加密.graffle
Labels: enhancement

#13 部分初始化脚本完成
  env_init/init.sh
  env_init/src/init_all.sh
  env_init/src/init_nvm.sh
  env_init/src/init_pm2.sh
  env_init/src/init_vapor.sh
  env_init/src/nvm.sh
  env_init/src/uninstall.sh
  env_init/src/uninstall_nvm.sh
  env_init/src/uninstall_pm2.sh
  env_init/src/uninstall_vapor.sh
  vault/init.sh
  vault/uninstall.sh
  vault/vault.hcl
Labels: enhancement

#14 修复了一些环境初始化脚本的问题
  README.md
  env_init/src/uninstall_vapor.sh
Labels: enhancement

#15 修复初始化脚本未正确卸载服务的问题
  env_init/init.sh
  env_init/src/init_all.sh
  env_init/src/uninstall.sh
Labels: enhancement

#16 0.2.3 更新环境初始化脚本
  env_init/src/init_all.sh
  env_init/src/uninstall.sh
Labels: bug

#17 Update uninstall_pm2.sh
  env_init/src/uninstall_pm2.sh
Labels: bug

#18 V0.2.3.5 Update uninstall_pm2.sh
  env_init/src/uninstall_pm2.sh
Labels: bug

#19 取消卸载 pm2 的设置，并更新了 README
  README.md
  env_init/src/uninstall.sh
Labels: enhancement

#20 将初始化脚本迁移到 https://github.com/SJJC-Team/whooshing-env-init 仓库下
  README.md
  env_init/init.sh
  env_init/src/init_all.sh
  env_init/src/init_nvm.sh
  env_init/src/init_pm2.sh
  env_init/src/init_vapor.sh
  env_init/src/nvm.sh
  env_init/src/uninstall.sh
  env_init/src/uninstall_nvm.sh
  env_init/src/uninstall_pm2.sh
  env_init/src/uninstall_vapor.sh
Labels: enhancement

#21 将 vault 和 percona 初始化脚本迁移到 https://github.com/SJJC-Team/whooshing-env-init
  percona_pgsql/create_service.sh
  vault/init.sh
  vault/uninstall.sh
  vault/vault.hcl
Labels: enhancement

#22 完成数据库创建，删除脚本，并修复权限错误
  percona_pgsql/create_database.sh
  percona_pgsql/create_module.sh
  percona_pgsql/create_server.sh
  percona_pgsql/create_service.sh
  percona_pgsql/list_module.sh
  percona_pgsql/list_pgserver.sh
  percona_pgsql/pg_hba.conf
  percona_pgsql/remove_database.sh
  percona_pgsql/remove_module.sh
  percona_pgsql/remove_server.sh
  percona_pgsql/vault_backup_database.sh
  percona_pgsql/vault_backup_module.sh
  percona_pgsql/vault_delete_secret.sh
  percona_pgsql/vault_login.sh
Labels: bug, enhancement

#23 初步完成解析配置文件创建服务的功能
  percona_pgsql/create_api.sh
  percona_pgsql/create_pg_server.sh
  percona_pgsql/create_service.sh
  percona_pgsql/example.yaml
  percona_pgsql/list_pg_server.sh
  percona_pgsql/remove_pg_server.sh
Labels: enhancement

#24 0.2.6 将项目代码从 shell 转为 swift
  .vscode/launch.json
  .vscode/settings.json
  percona_pgsql/create_pg_server.sh
  wsm-ctl/.gitignore
  wsm-ctl/Package.resolved
  wsm-ctl/Package.swift
  wsm-ctl/Sources/Config.swift
  wsm-ctl/Sources/Extensions.swift
  wsm-ctl/Sources/Module.swift
  wsm-ctl/Sources/Operations.swift
  wsm-ctl/Sources/PgDatabase.swift
  wsm-ctl/Sources/PgService.swift
  wsm-ctl/Sources/Shell/example.yaml
  wsm-ctl/Sources/Shell/pg_create_db.sh
  wsm-ctl/Sources/Shell/pg_create_service.sh
  wsm-ctl/Sources/Shell/pg_delete_db.sh
  wsm-ctl/Sources/Shell/pg_hba.conf
  wsm-ctl/Sources/Shell/pg_list_db.sh
  wsm-ctl/Sources/Shell/pg_restart_service.sh
  wsm-ctl/Sources/Shell/pg_start_service.sh
  wsm-ctl/Sources/Shell/pg_stop_service.sh
  wsm-ctl/Sources/Shell/pg_test_db.sh
  wsm-ctl/Sources/Shell/vault_db_backup.sh
  wsm-ctl/Sources/Shell/vault_delete_key.sh
  wsm-ctl/Sources/Shell/vault_get_key.sh
  wsm-ctl/Sources/Shell/vault_login.sh
  wsm-ctl/Sources/Shell/vault_module_backup.sh
  wsm-ctl/Sources/Shell/vault_new_engine.sh
  wsm-ctl/Sources/Shell/vault_new_key.sh
  wsm-ctl/Sources/WSM.swift
  wsm-ctl/Sources/Yaml-Extensions.swift
  wsm-ctl/Sources/Yaml.swift
Labels: enhancement
